#ifndef __WINVERSION_H
#define __WINVERSION_H

#include <windows.h>
#include <tchar.h>
#include <stdio.h>

#define BUFSIZE 256

#if _WIN_VER < 0x0600
#define PRODUCT_BUSINESS 0x6
#define PRODUCT_BUSINESS_N 0x10
#define PRODUCT_CLUSTER_SERVER 0x12
#define PRODUCT_DATACENTER_SERVER 0x8
#define PRODUCT_DATACENTER_SERVER_CORE 0xC
#define PRODUCT_DATACENTER_SERVER_CORE_V 0x27
#define PRODUCT_DATACENTER_SERVER_V 0x25
#define PRODUCT_ENTERPRISE 0x4
#define PRODUCT_ENTERPRISE_N 0x1B
#define PRODUCT_ENTERPRISE_SERVER 0xA
#define PRODUCT_ENTERPRISE_SERVER_CORE 0xE
#define PRODUCT_ENTERPRISE_SERVER_CORE_V 0x29
#define PRODUCT_ENTERPRISE_SERVER_IA64 0xF
#define PRODUCT_ENTERPRISE_SERVER_V 0x26
#define PRODUCT_HOME_BASIC 0x2
#define PRODUCT_HOME_BASIC_N 0x5
#define PRODUCT_HOME_PREMIUM 0x3
#define PRODUCT_HOME_PREMIUM_N 0x1A
#define PRODUCT_HOME_SERVER 0x13
#define PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT 0x1E
#define PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING 0x20
#define PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY 0x1F
#define PRODUCT_SERVER_FOR_SMALLBUSINESS 0x18
#define PRODUCT_SMALLBUSINESS_SERVER 0x9
#define PRODUCT_SMALLBUSINESS_SERVER_PREMIUM 0x19
#define PRODUCT_STANDARD_SERVER 0x7
#define PRODUCT_STANDARD_SERVER_CORE 0xD
#define PRODUCT_STANDARD_SERVER_CORE_V 0x28
#define PRODUCT_STANDARD_SERVER_V 0x24
#define PRODUCT_STARTER 0xB
#define PRODUCT_STORAGE_ENTERPRISE_SERVER 0x17
#define PRODUCT_STORAGE_EXPRESS_SERVER 0x14
#define PRODUCT_STORAGE_STANDARD_SERVER 0x15
#define PRODUCT_STORAGE_WORKGROUP_SERVER 0x16
#define PRODUCT_UNDEFINED 0x0
#define PRODUCT_ULTIMATE 0x1
#define PRODUCT_ULTIMATE_N 0x1C
#define PRODUCT_WEB_SERVER 0x11
#define PRODUCT_WEB_SERVER_CORE 0x1D

#define VER_SUITE_COMPUTE_SERVER 0x4000
#define VER_SUITE_STORAGE_SERVER 0x2000
#define VER_SUITE_WH_SERVER 0x8000

#define SM_SERVERR2 0x59
#endif

typedef void (WINAPI *PGNSI)(LPSYSTEM_INFO);
typedef BOOL (WINAPI *PGPI)(DWORD, DWORD, DWORD, DWORD, PDWORD);

BOOL GetOSDisplayString(LPTSTR osname, LPTSTR osver, DWORD* osbuild);

#endif /* __WINVERSION_H */